package com.jk.encryptionutils.ui;

public enum View {
	SYMMETRIC_ENCRYPTION,
	SYMMETRIC_DECRYPTION,
	SYMMETRIC_KEY_GENERATION,
	ASYMMETRIC_ENCRYPTION,
	ASYMMETRIC_DECRYPTION,
	ASYMMETRIC_KEY_GENERATION,
	ABOUT_APP;
}
